name: Go Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o webhook-configctl-linux-amd64 ./cmd/webhook-configctl
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: webhook-configctl-linux-amd64
        path: webhook-configctl-linux-amd64
